DELETE FROM FILM_LIKES;
DELETE FROM FILM_GENRES;
DELETE FROM FILMS_DIRECTORS;
DELETE FROM USER_FRIENDS;
DELETE FROM USERS;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM FILMS;
ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM GENRES;
ALTER TABLE GENRES ALTER COLUMN ID RESTART WITH 1;
DELETE FROM RATINGS;
ALTER TABLE RATINGS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM EVENTS;
ALTER TABLE EVENTS ALTER COLUMN EVENT_ID RESTART WITH 1;
DELETE FROM REVIEWS_RATINGS;
DELETE FROM REVIEWS;
ALTER TABLE REVIEWS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM DIRECTORS;
ALTER TABLE DIRECTORS ALTER COLUMN ID RESTART WITH 1;


INSERT INTO GENRES (name) VALUES
('Комедия'),
('Драма'),
('Мультфильм'),
('Триллер'),
('Документальный'),
('Боевик');

INSERT INTO RATINGS (NAME, DESCRIPTION) VALUES
('G', 'у фильма нет возрастных ограничений'),
('PG', 'детям рекомендуется смотреть фильм с родителями'),
('PG-13', 'детям до 13 лет просмотр не желателен'),
('R', 'лицам до 17 лет просматривать фильм можно только в присутствии взрослого'),
('NC-17', 'лицам до 18 лет просмотр запрещён.');
